name: Content Generator

on:
  schedule:
    # Run daily at 12 AM IST (6:30 PM UTC)
    - cron: '30 18 * * *'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg unzip
        
        # Install Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          # Install common dependencies if requirements.txt doesn't exist
          pip install requests selenium webdriver-manager
        fi
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
    
    - name: Create content directory
      run: |
        mkdir -p content
        echo "Content directory created/verified"
    
    - name: Run content downloader
      run: |
        echo "Starting content downloader..."
        python content_downloader.py
        echo "Content downloader completed"
      env:
        DISPLAY: ":99"
    
    - name: Run content organizer
      run: |
        echo "Starting content organizer..."
        python content_organizer.py
        echo "Content organizer completed"
    
    - name: Check for changes
      id: git-check
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected"
          git status --porcelain
        fi
    
    - name: Commit and push changes
      if: steps.git-check.outputs.has_changes == 'true'
      run: |
        git commit -m "Auto-update: Content generation $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
        git push origin ${{ github.ref_name }}
        echo "Changes committed and pushed successfully"
    
    - name: Upload content artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: generated-content-${{ github.run_number }}
        path: |
          content/
          images.json
        retention-days: 7
    
    - name: Summary
      if: always()
      run: |
        echo "## Content Generation Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Run ID:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Timestamp:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        
        if [ -d "content" ]; then
          content_files=$(find content -type f | wc -l)
          echo "- **Content files:** $content_files" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -f "images.json" ]; then
          echo "- **Images.json:** Updated" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ steps.git-check.outputs.has_changes }}" = "true" ]; then
          echo "- **Changes:** Committed and pushed" >> $GITHUB_STEP_SUMMARY
        else
          echo "- **Changes:** No changes detected" >> $GITHUB_STEP_SUMMARY
        fi