name: Hit Bot Runner

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  run-hit-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable

    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Verify Chrome installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Display config.json content
      run: |
        echo "Config.json contents:"
        cat config.json

    - name: Run hit bot
      run: |
        echo "Starting hit_bot.py at $(date)"
        python hit_bot.py
        echo "Completed hit_bot.py at $(date)"

    - name: Log completion
      run: |
        echo "Hit bot execution completed successfully"
        echo "Total browser instances launched based on config: $(($(jq '.[0].total_messages' config.json) * 5))"