name: Handle User Submission

on:
  repository_dispatch:
    types: [user_submission]
  workflow_dispatch:
    inputs:
      user_data:
        description: 'User data to append'
        required: true
        type: string

jobs:
  save-user-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Get user data
      id: get-data
      run: |
        if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
          echo "user_data=${{ github.event.client_payload.user_data }}" >> $GITHUB_OUTPUT
          echo "timestamp=${{ github.event.client_payload.timestamp }}" >> $GITHUB_OUTPUT
        else
          echo "user_data=${{ github.event.inputs.user_data }}" >> $GITHUB_OUTPUT
          echo "timestamp=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
        fi
    
    - name: Append user data to users.txt
      run: |
        echo "${{ steps.get-data.outputs.user_data }}" >> users.txt
        echo "User data appended: ${{ steps.get-data.outputs.user_data }}"
        echo "Timestamp: ${{ steps.get-data.outputs.timestamp }}"
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add users.txt
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add new user: ${{ steps.get-data.outputs.user_data }}"
          git push
          echo "Changes committed and pushed successfully"
        fi